### ISSUE TITLE
您好，请教一下如何从Uniprot获取蛋白质的结合位点

### ISSUE THREAD

**Issue by whitehat32** [JU-HuaY/MFR#1]
在Uniprot中可以找到蛋白质的结合位点，但是数据集中只包含了部分Uniprot记载的结合位点。如下图中AAK1有3行结合位点，分别是52-60、74、176，但是davis_binding_site.txt文件中只包含了74，176。
![image](https://user-images.githubusercontent.com/32572271/226506298-9d8d8e9a-b902-4d67-8960-1b4b4f284ea4.png)

**Comment by JU-HuaY** [comment]
你好，结合位点在uniprot中是动态更新的，是有不断发掘出新位点的可能，我在采集数据的时候也只是采用的当时状态的位点信息。另外位点信息也是通过脚本采集的，尽管我个人做了逐一校正，但仍然存在小部分遗漏问题，为给你带来的不便表示抱歉！

**Comment by whitehat32** [comment]
感谢您的回答
