### ISSUE TITLE
How to process drug SMILES to FCFPs and feature vector generated by GNN?

### ISSUE THREAD

**Issue by Chris-Tang6** [JU-HuaY/MFR#2]
Hello! In you paper _[MFR-DTA](https://academic.oup.com/bioinformatics/article/39/2/btad056/7008321)_, there are two types of drug feature as the **BioMLP Block** input. Specifically, the FCFPs and feat vec generated from GNN. However, I can't find out how to genearate these drug feature vector. Would you please show me more about this? Thank you😄

![image](https://user-images.githubusercontent.com/53926670/231461187-5ce230b7-1902-4aee-ac51-1684335a3f91.png)

**Comment by JU-HuaY** [comment]
I uploaded graph_features.py last month, it contains the details of the drug representation and the methods of feature vector generation using GNN.
